package com.codeguardian.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Code review request DTO
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReviewRequestDTO {
    
    /**
     * Review type: PROJECT, DIRECTORY, FILE, SNIPPET, GIT
     */
    @NotBlank(message = "Review type must not be empty")
    private String reviewType;

    /**
     * Project path (used when type is PROJECT or DIRECTORY)
     */
    private String projectPath;

    /**
     * Directory path (used when type is DIRECTORY)
     */
    private String directoryPath;

    /**
     * File path (used when type is FILE)
     */
    private String filePath;

    /**
     * Code snippet (used when type is SNIPPET)
     */
    private String codeSnippet;

    /**
     * Code language (used when type is SNIPPET)
     */
    private String language;

    /**
     * Git repository URL (used when type is GIT)
     */
    private String gitUrl;

    /**
     * Git username (optional)
     */
    private String gitUsername;

    /**
     * Git password or token (optional; held for the session only)
     * Git password/token (optional, session-scoped only)
     */
    private String gitPassword;

    /**
     * Task name (optional; auto-generated by default)
     * Task name (optional, auto-generated by default)
     */
    private String taskName;

    /**
     * AI model provider (optional; defaults to the configured provider)
     * Allowed values: OPENAI, QWEN, DEEPSEEK
     * AI model provider (optional, defaults to the configured provider)
     * Allowed values: OPENAI, QWEN, DEEPSEEK
     */
    private String modelProvider;

    /**
     * Whether to review with style rules only (no LLM call)
     * Whether to review using standard rules only (without calling the LLM)
     */
    private Boolean rulesOnly;

    /**
     * Rule template: ALIBABA, GOOGLE, AIRBNB, PEP8, CUSTOM
     * Ruleset: ALIBABA, GOOGLE, AIRBNB, PEP8, CUSTOM
     */
    private String ruleTemplate;

    /**
     * Custom style rules (only used when ruleTemplate=CUSTOM)
     * Custom rules (available only when ruleTemplate=CUSTOM)
     */
    private java.util.List<CustomRuleDTO> customRules;

    /**
     * Uploaded file list (used when type is DIRECTORY or PROJECT and contents are uploaded directly)
     * List of uploaded files (used when type is DIRECTORY or PROJECT and file content is uploaded directly)
     */
    private java.util.List<FileContentDTO> files;

    /**
     * Whether to enable RAG knowledge-base augmentation
     * Whether to enable RAG knowledge-base enhancement
     */
    private Boolean enableRag;
}
